name: Checks
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.95.0
        with:
          components: clippy, rustfmt
      - run: cargo install cargo-machete --version 0.9.2 --locked
      - run: ./scripts/check.sh
      - run: ./scripts/check_integration.sh
